### ISSUE TITLE
PERFORM Dataset Zenodo error

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-dataset#444]
The Zenodo crawler is currently choking on the PERFORM Dataset.

Error log:
```
PERFORM Dataset; one control subject, version 3824524 different from Zenodo vesion DOI 4059787, updating
Traceback (most recent call last):
  File "./scripts/crawl.py", line 70, in <module>
  File "/data/crawler/conp-dataset/scripts/Crawlers/BaseCrawler.py", line 272, in run
  File "/data/crawler/conp-dataset/scripts/Crawlers/ZenodoCrawler.py", line 293, in update_if_necessary
  File "/home/conp-bot/.local/lib/python3.6/site-packages/datalad/interface/utils.py", line 494, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/conp-bot/.local/lib/python3.6/site-packages/datalad/interface/utils.py", line 482, in return_func
    results = list(results)
  File "/home/conp-bot/.local/lib/python3.6/site-packages/datalad/interface/utils.py", line 413, in generator_func
    allkwargs):
  File "/home/conp-bot/.local/lib/python3.6/site-packages/datalad/interface/utils.py", line 552, in _process_results
    for res in results:
  File "/home/conp-bot/.local/lib/python3.6/site-packages/datalad/distribution/remove.py", line 274, in __call__
    for r in ds.repo.remove(list(to_reporemove), r=True):
  File "/home/conp-bot/.local/lib/python3.6/site-packages/datalad/support/gitrepo.py", line 328, in newfunc
    result = func(self, files_new, *args, **kwargs)
  File "/home/conp-bot/.local/lib/python3.6/site-packages/datalad/support/annexrepo.py", line 2695, in remove
    **kwargs)
  File "/home/conp-bot/.local/lib/python3.6/site-packages/datalad/support/gitrepo.py", line 328, in newfunc
    result = func(self, files_new, *args, **kwargs)
  File "/home/conp-bot/.local/lib/python3.6/site-packages/datalad/support/gitrepo.py", line 1437, in remove
    files, ['git', 'rm'] + to_options(**kwargs))
  File "/home/conp-bot/.local/lib/python3.6/site-packages/datalad/support/gitrepo.py", line 328, in newfunc
    result = func(self, files_new, *args, **kwargs)
  File "/home/conp-bot/.local/lib/python3.6/site-packages/datalad/support/gitrepo.py", line 2075, in _git_custom_command
    expect_fail=expect_fail)
  File "/home/conp-bot/.local/lib/python3.6/site-packages/datalad/cmd.py", line 141, in run_gitcommand_on_file_list_chunks
    results.append(func(cmd + ['--'] + file_chunk, *args, **kwargs))
  File "/home/conp-bot/.local/lib/python3.6/site-packages/datalad/cmd.py", line 1141, in run
    *args, **kwargs)
  File "/home/conp-bot/.local/lib/python3.6/site-packages/datalad/cmd.py", line 957, in run
    raise exc
datalad.support.exceptions.CommandError: CommandError: 'git rm -r -- data.zip' failed with exitcode 128 under /data/crawler/conp-dataset/projects/PERFORM_Dataset__one_control_subject [err: 'fatal: pathspec 'data.zip' did not match any files']
```

Guess on what is going on:
The dataset on Zenodo is a zip file. The content of that zip file (data.zip) has been added instead of data.zip but now that it needs to be updated, the crawler tries to delete data.zip, making the crawler crash.

@glatard do you agree with my assumption?

**Comment by cmadjar** [comment]
Making progress. Needed to reinstall miniconda and all the dependencies for the crawler to be working as by default `conp-bot` was using Python 2.7 and git-annex 7.*... Reinstalled miniconda for conp-bot and all the dependencies, including latest version of git-annex > 8.0.

Now, there is a new problem though. I believe this is due to the access token not having the right to see the latest update of the PERFORM dataset. 

Error message:
```
[INFO] http session: Authenticating into session for https://zenodo.org/api/files/b109eb90-ec6c-4c87-94ce-bb7c6950a0e8/data.zip?access_token=w4M00bgKOLzWDCHdFGeXc2wzaE9ftmedZAcneqTQEO9qQK4G3A7ez7CfOS7Y
Traceback (most recent call last):
  File "./scripts/crawl.py", line 70, in <module>
  File "/data/crawler/conp-dataset/scripts/Crawlers/BaseCrawler.py", line 272, in run
  File "/data/crawler/conp-dataset/scripts/Crawlers/ZenodoCrawler.py", line 305, in update_if_necessary
    {2}""".format(dataset["title"], dataset["doi_badge"],
  File "/data/crawler/conp-dataset/scripts/Crawlers/ZenodoCrawler.py", line 66, in _download_file
    d.download_url(link, archive=True)
  File "/home/conp-bot/.local/lib/python3.6/site-packages/datalad/distribution/dataset.py", line 503, in apply_func
    return f(**kwargs)
  File "/home/conp-bot/.local/lib/python3.6/site-packages/datalad/interface/utils.py", line 494, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/conp-bot/.local/lib/python3.6/site-packages/datalad/interface/utils.py", line 482, in return_func
    results = list(results)
  File "/home/conp-bot/.local/lib/python3.6/site-packages/datalad/interface/utils.py", line 469, in generator_func
    msg="Command did not complete successfully")
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
[{'action': 'download_url',
  'message': 'A non-interactive silent UI was asked for a response to a '
             'question: token. Title: You need to authenticate with '
             "'api.osf.io' credentials.. Additional arguments are not shown "
             "because 'hidden' is set. [dialog.py:question:139]",
  'path': '/data/crawler/conp-dataset/projects/PERFORM_Dataset__one_control_subject/',
  'status': 'error',
  'type': 'file'}]
```

Note: in the message it talks about the api.osf.io credentials but I am 100% confident this is Zenodo related as the crawler crashes when downloading the PERFORM dataset from Zenodo.

@glatard I have a feeling that the token used was associated to @joeyzhou98's account, unless it is associated with your account and @mathdugre did not grant you access to the latest version of the PERFORM dataset? 

As a temporary fix, I took the liberty to create a new token linked with my Zenodo account and changed it in `.conp_crawler_config.json` to see if that fixes the issue, which apparently it did based on the last run of the crawler.

@glatard let me know how you think we should handle the token thing or if the temporary fix is good enough for now and we can close the issue.

Thank you!

**Comment by cmadjar** [comment]
I changed the token of the crawler to be mine but now, the crawler does not want to update the PERFORM dataset. Will have to investigate more on this this week.

**Comment by cmadjar** [comment]
I could not find any solution as to why the crawler is failing on the VM so in the end, I crawled the dataset locally on my computer and the dataset is now updated.
